// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJqPLWEmTmwpUeRpTiWjLthxRs1QeqQgw',
    appId: '1:53311460557:web:58aa398f2eae75fb9e0584',
    messagingSenderId: '53311460557',
    projectId: 'myhack-55a43',
    authDomain: 'myhack-55a43.firebaseapp.com',
    databaseURL: 'https://myhack-55a43-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myhack-55a43.firebasestorage.app',
    measurementId: 'G-YBM0Z749SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    // Replaced the hardcoded key here as well
    apiKey:'AIzaSyBJqPLWEmTmwpUeRpTiWjLthxRs1QeqQgw',
    appId: '1:53311460557:android:97470527a45f2ca59e0584',
    messagingSenderId: '53311460557',
    projectId: 'myhack-55a43',
    databaseURL: 'https://myhack-55a43-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myhack-55a43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    // Replaced the hardcoded key here as well
    apiKey: 'AIzaSyBJqPLWEmTmwpUeRpTiWjLthxRs1QeqQgw',
    appId: '1:53311460557:ios:4446ad5cb37df0cd9e0584',
    messagingSenderId: '53311460557',
    projectId: 'myhack-55a43',
    databaseURL: 'https://myhack-55a43-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myhack-55a43.firebasestorage.app',
    iosClientId: '53311460557-q1b84adm70c9kf9ipk08eqtkjov12dh0.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJqPLWEmTmwpUeRpTiWjLthxRs1QeqQgw',
    appId: '1:53311460557:ios:4446ad5cb37df0cd9e0584',
    messagingSenderId: '53311460557',
    projectId: 'myhack-55a43',
    databaseURL: 'https://myhack-55a43-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myhack-55a43.firebasestorage.app',
    iosClientId: '53311460557-q1b84adm70c9kf9ipk08eqtkjov12dh0.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJqPLWEmTmwpUeRpTiWjLthxRs1QeqQgw',
    appId: '1:53311460557:web:d630db0b6a3c608e9e0584',
    messagingSenderId: '53311460557',
    projectId: 'myhack-55a43',
    authDomain: 'myhack-55a43.firebaseapp.com',
    databaseURL: 'https://myhack-55a43-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myhack-55a43.firebasestorage.app',
    measurementId: 'G-SL25DE6W22',
  );
}